version: '3.7'

services:
### PHP Container #########################################
  tfc:
    container_name: tfc
    hostname: tfc
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - .:/var/www/html/app
    depends_on:
      - tfcdb
    networks:
      - backend

### NGINX Container #########################################
  nginx:
    container_name: tfc_nginx
    hostname: nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - tfc
    ports:
      - 5000:80
    volumes:
      - .:/var/www/html/app
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

### POSTGRESS Container #########################################
  tfcdb:
    container_name: tfc_db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: tfc
      POSTGRES_USER: tfc-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - '54321:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

### Networks Setup ##########################################
networks:
  backend:
    driver: bridge

### Volumes Setup ##########################################
volumes:
  tfc:
  postgres-data:
    driver: "local"
  nginx-data:
    driver: "local"



